### ISSUE TITLE
Is Yelp planning on maintaining this at all?

### ISSUE THREAD

**Issue by cobbr2** [Yelp/schematizer#3]
It looks like this was maintained primarily as an internal project, and there was no corporate support for keeping it as an open-source project.  Is there any plan to open-source the current state of this system?  Still like your blog post about its use :), would love to try it out.

**Comment by ali-behjati** [comment]
Same question here. Wanna know whether you stopped using it (and your reason for it if so) or you are maintaining it internally.

**Comment by lsterk** [comment]
Hi all! Thanks for your interest. Yelp has been using and maintaining the service internally, which is why there haven't been any posts in this open source repo.

Posting the source code hopefully made the blog post series more interesting, but we found that keeping the service open source slowed down developer velocity. There are lots of Yelp idioms sprinkled throughout the code base, so it'd take a lot of work (and stray away from internal best practices) to maintain open-source compatibility.

We don't have plans to update this repo, but you can follow our [Engineering blog](https://engineeringblog.yelp.com/) for more content from Yelp Engineering!
